import './globals.css'
import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from './globals/design-system'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CheckPoint - Check in system',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }: { children: React.ReactNode }): React.JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
